title:              Simple Multiphysics Simulation Tutorials
email:              betancourt.jo@icloud.com
description:        Simple step-by-step guides to make your own simulations.
author:             Jo Betancourt
baseurl:            ""
url:                "https://jobetancourt.github.io"

# Social Profiles
twitter_username:   
github_username:    jobetancourt
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5bundle exec jekyll serve
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
